version: '3'
services:
  credentials:
    image: "larrycai/openldap"
    container_name: servicio_ldap_76067384
    volumes:
      - ./user.ldif:/home/user.ldif
    depends_on: 
      - nextcloud01
      - nextcloud02
      - nextcloud03
    ports:
      - 389
  nextcloud01:
    image: "nextcloud:21.0.0-apache"
    restart: always
    container_name: servicio_nextcloud01_76067384
    depends_on: 
      - mariadb
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_HOST=mariadb
      - NEXTCLOUD_ADMIN_USER=nextcloud
      - NEXTCLOUD_ADMIN_PASSWORD=nextcloud
  nextcloud02:
    image: "nextcloud:21.0.0-apache"
    restart: always
    container_name: servicio_nextcloud02_76067384
    depends_on: 
      - mariadb
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_HOST=mariadb
      - NEXTCLOUD_ADMIN_USER=nextcloud
      - NEXTCLOUD_ADMIN_PASSWORD=nextcloud
  nextcloud03:
    image: "nextcloud:21.0.0-apache"
    restart: always
    container_name: servicio_nextcloud03_76067384
    depends_on: 
      - mariadb
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_HOST=mariadb
      - NEXTCLOUD_ADMIN_USER=nextcloud
      - NEXTCLOUD_ADMIN_PASSWORD=nextcloud
  mariadb:
    image: "mariadb:10.4.8-bionic"
    container_name: servicio_mariadb_76067384
    command: "--transaction-isolation=READ-COMMITTED --binlog-format=ROW"
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
  nginx:
    image: nginx:latest
    container_name: servicio_nginx_76067384
    volumes:
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    restart: always
    ports:
      - 31009:80
volumes:
  nextcloud:
  db:
